# Vaultica Keystone CI Gatekeeping Workflow
#
# Copy this file to your consumer project's .github/workflows/ directory.
# It checks that the keystone submodule is up to date and tokens are built.
#
# Usage in consumer project:
#   1. Copy to .github/workflows/keystone-check.yml
#   2. Adjust paths if keystone is in a different location
#   3. The workflow runs on PRs and pushes to main

name: Keystone Version Check

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  check-keystone:
    name: Verify Keystone Tokens
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: vaultica-keystone/pnpm-lock.yaml

      - name: Check keystone submodule version
        id: version-check
        run: |
          cd vaultica-keystone

          # Fetch latest from remote
          git fetch origin main

          LOCAL_COMMIT=$(git rev-parse HEAD)
          REMOTE_COMMIT=$(git rev-parse origin/main 2>/dev/null || echo "")

          echo "local_commit=${LOCAL_COMMIT}" >> $GITHUB_OUTPUT
          echo "remote_commit=${REMOTE_COMMIT}" >> $GITHUB_OUTPUT

          echo "ðŸ“¦ Keystone Submodule Status"
          echo "   Local:  ${LOCAL_COMMIT:0:8}"
          echo "   Remote: ${REMOTE_COMMIT:0:8}"

          if [ -n "$REMOTE_COMMIT" ] && [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ]; then
            echo ""
            echo "::warning::Keystone submodule is outdated"
            echo "outdated=true" >> $GITHUB_OUTPUT
          else
            echo ""
            echo "âœ… Keystone is up to date"
            echo "outdated=false" >> $GITHUB_OUTPUT
          fi

      - name: Verify tokens are built
        run: |
          echo "ðŸ” Checking built tokens..."

          MISSING=""
          for file in theme.css tailwind.config.js tokens.js tokens.d.ts; do
            if [ ! -f "vaultica-keystone/dist/$file" ]; then
              MISSING="$MISSING $file"
            fi
          done

          if [ -n "$MISSING" ]; then
            echo "::error::Missing token files:$MISSING"
            echo ""
            echo "Run in keystone directory:"
            echo "  pnpm install && pnpm run build"
            exit 1
          fi

          echo "âœ… All token files present"

      - name: Verify token hash
        if: hashFiles('.keystone-hash') != ''
        run: |
          echo "ðŸ” Verifying token hash..."

          # Calculate current hash
          CURRENT_HASH=$(cat vaultica-keystone/dist/theme.css \
            vaultica-keystone/dist/tailwind.config.js \
            vaultica-keystone/dist/tokens.js \
            vaultica-keystone/dist/tokens.d.ts 2>/dev/null | sha256sum | cut -d' ' -f1)

          STORED_HASH=$(cat .keystone-hash | tr -d '[:space:]')

          echo "   Stored:  ${STORED_HASH:0:16}..."
          echo "   Current: ${CURRENT_HASH:0:16}..."

          if [ "$CURRENT_HASH" != "$STORED_HASH" ]; then
            echo ""
            echo "::error::Token hash mismatch! Update .keystone-hash file."
            exit 1
          fi

          echo ""
          echo "âœ… Token hash verified"

      - name: Summary
        if: always()
        run: |
          echo "## Keystone Check Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.version-check.outputs.outdated }}" == "true" ]; then
            echo "âš ï¸ **Submodule Status:** Outdated" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Update with:" >> $GITHUB_STEP_SUMMARY
            echo '```bash' >> $GITHUB_STEP_SUMMARY
            echo 'git submodule update --remote vaultica-keystone' >> $GITHUB_STEP_SUMMARY
            echo 'cd vaultica-keystone && pnpm run build && cd ..' >> $GITHUB_STEP_SUMMARY
            echo 'git add vaultica-keystone' >> $GITHUB_STEP_SUMMARY
            echo 'git commit -m "chore: update keystone to latest"' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "âœ… **Submodule Status:** Up to date" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Commit | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Local | \`${{ steps.version-check.outputs.local_commit }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Remote | \`${{ steps.version-check.outputs.remote_commit }}\` |" >> $GITHUB_STEP_SUMMARY

  # Optional: Block merge if outdated (strict mode)
  # Uncomment this job to make outdated keystone a blocking failure
  #
  # block-if-outdated:
  #   name: Block Outdated Keystone
  #   runs-on: ubuntu-latest
  #   needs: check-keystone
  #   if: needs.check-keystone.outputs.outdated == 'true'
  #   steps:
  #     - name: Fail if outdated
  #       run: |
  #         echo "::error::Cannot merge with outdated keystone submodule"
  #         exit 1
